// scenarios/documentLibrary.js

/**
 * Document library - MIGRATED TO NEW MANIFEST SYSTEM
 * 
 * This file now provides a compatibility layer for the new JSON manifest system.
 * Documents are now stored in /scenarios/documentManifest.json with public/secret separation.
 * 
 * Benefits of new system:
 * - Legal educators can edit content without touching code
 * - Public content is human-readable while secrets remain protected
 * - Better separation of content from application logic
 * - Easier scenario creation and maintenance
 */

import { documentManifestLoader } from '../services/documentManifestLoader.js';

// Legacy compatibility object - now loads from manifest
export const CASE_DOCUMENTS = {
    
    // Homicide Case: John Sterling (Eyewitness with affair secret)
    'Homicide-PKM-2024-031': {
        documents: [
            {
                fileName: 'hotel_receipt_starlight_motel.txt',
                documentType: 'receipt',
                exhibitLetter: 'A',
                content: `STARLIGHT MOTEL
1247 Old Highway 6, Houston, TX 77077
Phone: (281) 555-0199

Room 147 - Check-in Receipt
Date: March 23, 2024
Time: 11:47 PM

Guest: C. Williams
Room Rate: $89.00 + tax
Total: $96.68

Payment: Cash
Duration: 4 hours

Manager: Rick Patterson
Thank you for staying with us!

*** CONFIDENTIAL RECEIPT ***`,
                metadata: {
                    dates: ['March 23, 2024'],
                    parties: ['C. Williams', 'Rick Patterson'],
                    keyTopics: ['hotel', 'receipt', 'starlight', 'motel', 'cash', 'payment'],
                    relevance: 'Could contradict witness claim about being alone at motel'
                }
            },
            {
                fileName: 'sterling_phone_records.txt',
                documentType: 'phone_records',
                exhibitLetter: 'B',
                content: `TEXACORP SOLUTIONS - CORPORATE PHONE RECORDS
Employee: Johnathan Sterling
Phone: (713) 555-0142
Date Range: March 23-24, 2024

OUTGOING CALLS:
23:52 - (713) 555-0088 - Duration: 4 min 23 sec
00:15 - (713) 555-0088 - Duration: 1 min 47 sec
00:43 - Anonymous Tip Line - Duration: 2 min 12 sec

INCOMING CALLS:
23:48 - (713) 555-0088 - Duration: 2 min 15 sec

Note: (713) 555-0088 registered to C. Williams (Personal)

Generated by Telecom Analytics Dept.
Confidential - Internal Use Only`,
                metadata: {
                    dates: ['March 23, 2024', 'March 24, 2024'],
                    parties: ['Johnathan Sterling', 'C. Williams'],
                    keyTopics: ['phone', 'records', 'calls', 'anonymous', 'tip'],
                    relevance: 'Shows communication with C. Williams during incident timeframe'
                }
            },
            {
                fileName: 'witness_statement_initial.txt',
                documentType: 'statement',
                exhibitLetter: 'C',
                content: `HOUSTON POLICE DEPARTMENT
WITNESS STATEMENT - INITIAL REPORT

Case Number: HPD-2024-031
Date: March 24, 2024
Time: 14:22

Witness: John Sterling
Address: [REDACTED] Memorial, Houston, TX
Phone: (713) 555-0142

STATEMENT:
I was driving home from a client dinner around 11:30 PM on March 23rd. I felt extremely tired and pulled into the Starlight Motel parking lot to rest for a few minutes before continuing home. 

While sitting in my car, I heard shouting between two men near room 147. I saw one man, approximately 30 years old with dark hair and a scar over his left eye, stab another man with what appeared to be a knife. The incident lasted about 2-3 minutes.

I was too shocked to intervene and drove home immediately. I called the tip line the next day because I felt it was my civic duty.

I did not know either individual involved.

Witness Signature: J. Sterling
Officer: Det. Maria Rodriguez #2847`,
                metadata: {
                    dates: ['March 23, 2024', 'March 24, 2024'],
                    parties: ['John Sterling', 'Maria Rodriguez'],
                    keyTopics: ['witness', 'statement', 'client', 'dinner', 'tired', 'motel'],
                    relevance: 'Official witness statement with potential inconsistencies'
                }
            }
        ]
    },

    // Domestic Violence Case: Margaret Chen (Observant Neighbor)
    'Civil-DV-2024-047': {
        documents: [
            {
                fileName: 'chen_journal_excerpts.txt',
                documentType: 'journal',
                exhibitLetter: 'A',
                content: `PERSONAL JOURNAL - MARGARET CHEN
[Selected Excerpts - April to December 2007]

April 15, 2007:
Terrible scene next door today. Jay was screaming at Sarah again. Saw him with what looked like a knife at his own throat by the front gate around 3 PM. Called 911. Police came but he was gone by then. Sarah seemed terrified.

November 3, 2007:
Worst incident yet. From kitchen window I could see Jay hitting Sarah in the backyard. It went on for at least 15 minutes. I should have called police but I was scared he would see me. Feel terrible about this.

November 15, 2007:
Jay's truck has been parked across the street every evening this week. He just sits there watching the house. Sarah's car hasn't moved in days. I'm worried about her.

December 1, 2007:
Saw Jay following Sarah's car when she left for work this morning. This has to stop. I'm documenting everything now in case it's needed later.

[End of excerpts]`,
                metadata: {
                    dates: ['April 15, 2007', 'November 3, 2007', 'November 15, 2007', 'December 1, 2007'],
                    parties: ['Margaret Chen', 'Jay', 'Sarah'],
                    keyTopics: ['domestic', 'violence', 'journal', 'incidents', 'documentation'],
                    relevance: 'Detailed contemporaneous documentation of abuse patterns'
                }
            },
            {
                fileName: 'police_report_april.txt',
                documentType: 'police_report',
                exhibitLetter: 'B',
                content: `METRO POLICE DEPARTMENT
INCIDENT REPORT

Report #: MPD-2007-4829
Date: April 15, 2007
Time: 15:23
Location: 1247 Elm Street

INCIDENT TYPE: Domestic Disturbance
REPORTING OFFICER: Officer James Mitchell #447

SUMMARY:
Responded to 911 call regarding domestic disturbance. Caller (Margaret Chen, 1249 Elm Street) reported male subject with knife threatening self-harm at neighboring residence.

Upon arrival, no subjects present at scene. Spoke with complainant who described male subject (identified as Jay Dooley) holding knife to throat and cutting wrist. Complainant observed incident from her property.

No evidence of incident found at scene. No blood observed. Attempted contact with resident (Sarah Martinez) - no response.

DISPOSITION: Unable to locate subjects. Report filed for documentation.

Officer Signature: J. Mitchell #447`,
                metadata: {
                    dates: ['April 15, 2007'],
                    parties: ['James Mitchell', 'Margaret Chen', 'Jay Dooley', 'Sarah Martinez'],
                    keyTopics: ['police', 'report', 'domestic', 'disturbance', 'knife'],
                    relevance: 'Official police documentation of first reported incident'
                }
            }
        ]
    },

    // Employment Case Template (can be expanded)
    'Employment-WB-2024-089': {
        documents: [
            {
                fileName: 'hr_complaint_form.txt',
                documentType: 'complaint',
                exhibitLetter: 'A',
                content: `CORPORATE HR DEPARTMENT
FORMAL COMPLAINT FORM

Employee: [Name Redacted]
Department: Sales
Date Filed: June 15, 2024
Complaint ID: HR-2024-0234

NATURE OF COMPLAINT:
Whistleblower retaliation following report of financial irregularities in Q1 2024 sales figures.

SPECIFIC INCIDENTS:
1. Demotion from Senior Sales Associate to Junior Associate (June 1, 2024)
2. Salary reduction from $85,000 to $62,000 annually
3. Exclusion from team meetings and client communications
4. Hostile work environment created by management

SUPPORTING DOCUMENTATION:
- Email correspondence with CFO regarding irregularities
- Performance reviews (2022-2024)
- Witness statements from colleagues

Complainant Signature: [Redacted]
Date: June 15, 2024`,
                metadata: {
                    dates: ['June 15, 2024', 'June 1, 2024'],
                    parties: ['HR Department', 'CFO'],
                    keyTopics: ['whistleblower', 'retaliation', 'complaint', 'demotion', 'salary'],
                    relevance: 'Formal documentation of retaliation claims'
                }
            }
        ]
    }
};

/**
 * Gets all documents for a specific case - now loads from manifest
 * @param {string} caseReference - Case reference ID
 * @returns {Promise<Array>} Array of document objects
 */
export async function getDocumentsForCase(caseReference) {
    try {
        return await documentManifestLoader.getDocumentsForCase(caseReference);
    } catch (error) {
        console.warn('Failed to load documents from manifest, falling back to legacy:', error);
        // Fallback to legacy system if manifest fails
        const caseData = CASE_DOCUMENTS[caseReference];
        return caseData ? caseData.documents : [];
    }
}

/**
 * Gets a specific document by case and exhibit letter
 * @param {string} caseReference - Case reference ID  
 * @param {string} exhibitLetter - Exhibit letter (A, B, C, etc.)
 * @returns {Promise<Object|null>} Document object or null if not found
 */
export async function getDocumentByExhibit(caseReference, exhibitLetter) {
    const documents = await getDocumentsForCase(caseReference);
    return documents.find(doc => doc.exhibitLetter === exhibitLetter) || null;
}

/**
 * Converts case documents to the format expected by documentService
 * @param {string} caseReference - Case reference ID
 * @returns {Promise<Array>} Array of formatted document objects
 */
export async function formatCaseDocumentsForService(caseReference) {
    try {
        // New manifest system already returns properly formatted documents
        return await documentManifestLoader.getDocumentsForCase(caseReference);
    } catch (error) {
        console.warn('Failed to load from manifest, using legacy format:', error);
        // Fallback to legacy formatting
        const documents = await getDocumentsForCase(caseReference);
        
        return documents.map(doc => ({
            id: `case_doc_${caseReference}_${doc.exhibitLetter}`,
            fileName: doc.fileName,
            exhibitLetter: doc.exhibitLetter,
            textContent: doc.content,
            tokenCount: Math.ceil(doc.content.split(/\s+/).length * 0.75), // Estimate tokens
            summary: doc.content.length > 2000 ? createDocumentSummary(doc.content) : null,
            metadata: {
                ...doc.metadata,
                documentType: doc.documentType,
                isPreBuilt: true,
                caseReference: caseReference
            },
            uploadDate: new Date().toISOString(),
            isActive: false
        }));
    }
}

/**
 * Creates a summary for long documents
 * @param {string} content - Document content
 * @returns {string} Document summary
 */
function createDocumentSummary(content) {
    const lines = content.split('\n').filter(line => line.trim().length > 0);
    if (lines.length <= 5) return content;
    
    // Take first 2 and last 2 lines with indicator
    return lines.slice(0, 2).join('\n') + 
           '\n\n[... content abbreviated ...]\n\n' + 
           lines.slice(-2).join('\n');
}